Action()
{
	lr_vuser_status_message("IP address: %s", lr_get_vuser_ip());
	
	//get on dock date: 02/11/2014
	lr_save_string("07/22/2014", "LR_OnDockDate");
	
	//02%2F11%2F2014
	web_convert_param(
		"LR_OnDockDate_URL",
		"SourceString={LR_OnDockDate}",
		"SourceEncoding=PLAIN",
		"TargetEncoding=URL",
		LAST);
	
	//get due date: 02/13/2014
	lr_save_string("07/22/2014", "LR_DueDate");
	
	//02%2F13%2F2014
	web_convert_param(
		"LR_DueDate_URL",
		"SourceString={LR_DueDate}",
		"SourceEncoding=PLAIN",
		"TargetEncoding=URL",
		LAST);
	

	web_url("qrtapp", 
		"URL=http://qrt-staging.avnet.com/qrtapp", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t5.inf", 
		"Mode=HTML", 
		LAST);

	web_url("eaidologin", 
		"URL=https://edge-test.avnet.com/eai/EAIavnet/eaidologin", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://edge-test.avnet.com/vouchfor?avnet&http://qrt-staging.avnet.com/qrtapp", 
		"Snapshot=t6.inf", 
		"Mode=HTML", 
		LAST);


	/*login as 031214*/
	
	lr_start_transaction("SMR_Login");

	web_reg_find("Search=Body",
		"Text=View Work Queue For",
		LAST);

	web_submit_form("eaidologin_2", 
		"Snapshot=t7.inf", 
		ITEMDATA, 
		"Name=username", "Value={LoginID}", ENDITEM, 
		"Name=password", "Value=Tivoli01", ENDITEM, 
		EXTRARES, 
		"Url=http://qrt-staging.avnet.com/qrtapp/resources/images/iQuoteIcons.png", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		"Url=http://qrt-staging.avnet.com/qrtapp/resources/css/icons/iquote-logo.png", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		"Url=http://qrt-staging.avnet.com/qrtapp/resources/images/nav-arrow.gif", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		"Url=http://qrt-staging.avnet.com/qrtapp/resources/css/icons/icon-expanded.png", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		"Url=http://qrt-staging.avnet.com/qrtapp/javax.faces.resource/images/ui-icons_38667f_256x240.png.jsf?ln=primefaces-aristo", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		"Url=http://qrt-staging.avnet.com/qrtapp/javax.faces.resource/images/ui-icons_616161_256x240.png.jsf?ln=primefaces-aristo", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", ENDITEM, 
		LAST);
	
	lr_end_transaction("SMR_Login", LR_AUTO);

	/*click create quote*/
	
	//-524181132703387522:3741782905069124776
	web_reg_save_param_ex(
		"ParamName=ViewState",
		"LB=javax.faces.ViewState\" value=\"",
		"RB=\" autocomplete",
		SEARCH_FILTERS,
		"Scope=Body",
		LAST);

	web_reg_find("Search=Body",
		"Text=Input Method",
		LAST);

	web_url("qrt_redirect", 
		"URL=http://qrt-staging.avnet.com/qrtapp/qrt_redirect?conversationContext=1&convName=createQuoteBackingBean&nextView=pages/smx/CreateQuote.jsf", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/Dashboard.jsf", 
		"Snapshot=t10.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=javax.faces.resource/qrt_create_quote.js.jsf?ln=javascript&conversationContext=1", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", ENDITEM, 
		LAST);
	
	//-524181132703387522%3A3741782905069124776
	web_convert_param(
		"ViewState_URL",
		"SourceString={ViewState}",
		"SourceEncoding=HTML",
		"TargetEncoding=URL",
		LAST);

	/*click part search icon*/

	lr_think_time(18);
	

	web_add_header("Faces-Request", "partial/ajax");

	web_submit_data("CreateQuote.jsf", 
		"Action=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t11.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=javax.faces.partial.ajax", "Value=true", ENDITEM, 
		"Name=javax.faces.source", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=javax.faces.partial.execute", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=javax.faces.partial.render", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=createQuote:partSearchDial:dial1", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=createQuote:partSearchDial:dial1_contentLoad", "Value=true", ENDITEM, 
		"Name=createQuote", "Value=createQuote", ENDITEM, 
		"Name=createQuote:customDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:customerOnDockDate", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscAcctNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscBranch", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanQuantity", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustomerPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:originalPartNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanLineItem", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:enableAddLine", "Value=true", ENDITEM, 
		"Name=createQuote:biSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:billToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biNumber", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:customerTLA", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:project", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biTLAStatusSmart", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biSearchDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:createQuoteErrorMsgs", "Value=", ENDITEM, 
		"Name=createQuote:messagesPanel_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:selectedQuoteType", "Value=RFQ", ENDITEM, 
		"Name=createQuote:nationalFlag", "Value=false", ENDITEM, 
		"Name=createQuote:inSelInputMethod", "Value=Manual", ENDITEM, 
		"Name=createQuote:customerFound", "Value=false", ENDITEM, 
		"Name=createQuote:idNAcFlag", "Value=false", ENDITEM, 
		"Name=createQuote:billtosmart_input", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccountH", "Value=", ENDITEM, 
		"Name=createQuote:contactNameSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerAccount", "Value=", ENDITEM, 
		"Name=createQuote:billToAttention", "Value=", ENDITEM, 
		"Name=createQuote:shipToAttention", "Value=", ENDITEM, 
		"Name=createQuote:contactPhone", "Value=", ENDITEM, 
		"Name=createQuote:endCustomername", "Value=", ENDITEM, 
		"Name=createQuote:billToAddress", "Value=", ENDITEM, 
		"Name=createQuote:shipToAddress", "Value=", ENDITEM, 
		"Name=createQuote:contactEmail", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCity", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerStateProvince", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerZip", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCountry", "Value=US", ENDITEM, 
		"Name=createQuote:customeronDockDate_input", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:followUpDate_input", "Value=", ENDITEM, 
		"Name=createQuote:dateDuetoCustomer_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:dateDuetoSales_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:projectBoard", "Value=", ENDITEM, 
		"Name=createQuote:customerQuote", "Value=", ENDITEM, 
		"Name=createQuote:customersHazmatPreference", "Value=", ENDITEM, 
		"Name=createQuote:creditCategory", "Value=", ENDITEM, 
		"Name=createQuote:creditReview", "Value=", ENDITEM, 
		"Name=createQuote:resaleCertificate", "Value=", ENDITEM, 
		"Name=createQuote:registrationMatching", "Value=Auto Match", ENDITEM, 
		"Name=createQuote:creditLimit", "Value=", ENDITEM, 
		"Name=createQuote:paymentTerms", "Value=", ENDITEM, 
		"Name=createQuote:statementofAssurance", "Value=", ENDITEM, 
		"Name=createQuote:specialHandlingCode", "Value=", ENDITEM, 
		"Name=createQuote:creditBalance", "Value=", ENDITEM, 
		"Name=createQuote:channelCode", "Value=", ENDITEM, 
		"Name=createQuote:deniedPartyStatus", "Value=", ENDITEM, 
		"Name=createQuote:creditAvailable", "Value=", ENDITEM, 
		"Name=createQuote:taxIndicator", "Value=", ENDITEM, 
		"Name=createQuote:headerComments", "Value=", ENDITEM, 
		"Name=createQuote:customerSearch_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:newLine", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:comments", "Value=", ENDITEM, 
		"Name=createQuote:createLineItems_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:idHidErrorPresent", "Value=false", ENDITEM, 
		"Name=javax.faces.ViewState", "Value={ViewState}", ENDITEM, 
		EXTRARES, 
		"Url=/qrtapp/javax.faces.resource/spacer/dot_clear.gif.jsf?ln=primefaces", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", ENDITEM, 
		"Url=/qrtapp/javax.faces.resource/images/ui-bg_flat_0_2d5972_40x100.png.jsf?ln=primefaces-aristo", "Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", ENDITEM, 
		LAST);

	/*enter CP0010R7500JB14*/

	/*click search*/

	lr_think_time(22);
	
	lr_start_transaction("BP15_PartSearch_SearchPart");
	
	//Vishay / Dale (DAL)
	web_reg_save_param_ex(
		"ParamName=MFGCD",
		"LB=\"mfgCd\":\"",
		"RB=\"",
		SEARCH_FILTERS,
		"Scope=Body",
		LAST);

	web_add_header("Faces-Request", "partial/ajax");
	web_submit_data("CreateQuote.jsf_2", 
		"Action=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t12.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=javax.faces.partial.ajax", "Value=true", ENDITEM, 
		"Name=javax.faces.source", "Value=createQuote:partSearchDial:searchPartNumber", ENDITEM, 
		"Name=javax.faces.partial.execute", "Value=createQuote:partSearchDial:searchPartNumber createQuote:partSearchDial:partNumber createQuote:partSearchDial:searchDlgManufacturerCodeSmart createQuote:partSearchDial:searchDlgCommodityCodeSmart createQuote:partSearchDial:beanCustAccountNo createQuote:partSearchDial:beanQuantity createQuote:partSearchDial:beanLineItem createQuote:partSearchDial:shipToAccountNo createQuote:partSearchDial:customerOnDockDate createQuote:partSearchDial:miscAcctNo createQuote"
		":partSearchDial:miscBranch", ENDITEM, 
		"Name=javax.faces.partial.render", "Value=createQuote:partSearchDial:result", ENDITEM, 
		"Name=createQuote:partSearchDial:searchPartNumber", "Value=createQuote:partSearchDial:searchPartNumber", ENDITEM, 
		"Name=createQuote", "Value=createQuote", ENDITEM, 
		"Name=createQuote:customDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:customerOnDockDate", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:partSearchDial:miscAcctNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscBranch", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanQuantity", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustomerPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:originalPartNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanLineItem", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:enableAddLine", "Value=true", ENDITEM, 
		"Name=createQuote:partSearchDial:partNumber", "Value={PartID}", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgManufacturerCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgCommodityCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:selectedPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchPartDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:billToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biNumber", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:customerTLA", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:project", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biTLAStatusSmart", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biSearchDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:createQuoteErrorMsgs", "Value=", ENDITEM, 
		"Name=createQuote:messagesPanel_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:selectedQuoteType", "Value=RFQ", ENDITEM, 
		"Name=createQuote:nationalFlag", "Value=false", ENDITEM, 
		"Name=createQuote:inSelInputMethod", "Value=Manual", ENDITEM, 
		"Name=createQuote:customerFound", "Value=false", ENDITEM, 
		"Name=createQuote:idNAcFlag", "Value=false", ENDITEM, 
		"Name=createQuote:billtosmart_input", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccountH", "Value=", ENDITEM, 
		"Name=createQuote:contactNameSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:endCustomerAccount", "Value=", ENDITEM, 
		"Name=createQuote:billToAttention", "Value=", ENDITEM, 
		"Name=createQuote:shipToAttention", "Value=", ENDITEM, 
		"Name=createQuote:contactPhone", "Value=", ENDITEM, 
		"Name=createQuote:endCustomername", "Value=", ENDITEM, 
		"Name=createQuote:billToAddress", "Value=", ENDITEM, 
		"Name=createQuote:shipToAddress", "Value=", ENDITEM, 
		"Name=createQuote:contactEmail", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCity", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerStateProvince", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerZip", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCountry", "Value=US", ENDITEM, 
		"Name=createQuote:customeronDockDate_input", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:followUpDate_input", "Value=", ENDITEM, 
		"Name=createQuote:dateDuetoCustomer_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:dateDuetoSales_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:projectBoard", "Value=", ENDITEM, 
		"Name=createQuote:customerQuote", "Value=", ENDITEM, 
		"Name=createQuote:customersHazmatPreference", "Value=", ENDITEM, 
		"Name=createQuote:creditCategory", "Value=", ENDITEM, 
		"Name=createQuote:creditReview", "Value=", ENDITEM, 
		"Name=createQuote:resaleCertificate", "Value=", ENDITEM, 
		"Name=createQuote:registrationMatching", "Value=Auto Match", ENDITEM, 
		"Name=createQuote:creditLimit", "Value=", ENDITEM, 
		"Name=createQuote:paymentTerms", "Value=", ENDITEM, 
		"Name=createQuote:statementofAssurance", "Value=", ENDITEM, 
		"Name=createQuote:specialHandlingCode", "Value=", ENDITEM, 
		"Name=createQuote:creditBalance", "Value=", ENDITEM, 
		"Name=createQuote:channelCode", "Value=", ENDITEM, 
		"Name=createQuote:deniedPartyStatus", "Value=", ENDITEM, 
		"Name=createQuote:creditAvailable", "Value=", ENDITEM, 
		"Name=createQuote:taxIndicator", "Value=", ENDITEM, 
		"Name=createQuote:headerComments", "Value=", ENDITEM, 
		"Name=createQuote:customerSearch_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:newLine", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:comments", "Value=", ENDITEM, 
		"Name=createQuote:createLineItems_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:idHidErrorPresent", "Value=false", ENDITEM, 
		"Name=javax.faces.ViewState", "Value={ViewState}", ENDITEM, 
		LAST);
	
	//Vishay+%2F+Dale+(DAL)
	web_convert_param(
		"MFGCD_URL",
		"SourceString={MFGCD}",
		"SourceEncoding=HTML",
		"TargetEncoding=URL",
		LAST);

	web_add_header("Faces-Request", "partial/ajax");
	web_custom_request("CreateQuote.jsf_3", 
		"URL=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"Resource=0", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t13.inf", 
		"Mode=HTML", 
		"EncType=application/x-www-form-urlencoded; charset=UTF-8", 
		"Body=javax.faces.partial.ajax=true&javax.faces.source=createQuote%3ApartSearchDial%3Aj_idt267&javax.faces.partial.execute=%40all&javax.faces.partial.render=+createQuote%3ApartSearchDial%3AaddToLineButton&createQuote%3ApartSearchDial%3Aj_idt267=createQuote%3ApartSearchDial%3Aj_idt267&createQuote=createQuote&createQuote%3AcustomDlg%3AcustomerName=&createQuote%3AcustomDlg%3AcustomerAccount_input=&createQuote%3AcustomDlg%3Abranch_input=&createQuote%3AcustomDlg%3AsearchCustomerDataTable_selection=&"
		"createQuote%3AendcustomDlg%3AcustomerName=&createQuote%3AendcustomDlg%3AcustomerAccount_input=&createQuote%3AendcustomDlg%3Abranch_input=&createQuote%3AendcustomDlg%3AsearchCustomerDataTable_selection=&createQuote%3AmisendcustomDlg%3AcustomerName=&createQuote%3AmisendcustomDlg%3AcustomerAccount_input=&createQuote%3AmisendcustomDlg%3Abranch_input=&createQuote%3AmisendcustomDlg%3AsearchCustomerDataTable_selection=&createQuote%3ApartSearchDial%3AshipToAccountNo=&"
		"createQuote%3ApartSearchDial%3AcustomerOnDockDate={LR_OnDockDate_URL}&createQuote%3ApartSearchDial%3AmiscAcctNo=&createQuote%3ApartSearchDial%3AmiscBranch=&createQuote%3ApartSearchDial%3AbeanCustAccountNo=&createQuote%3ApartSearchDial%3AbeanQuantity=&createQuote%3ApartSearchDial%3AbeanCustomerPart=&createQuote%3ApartSearchDial%3AoriginalPartNumber=&createQuote%3ApartSearchDial%3AbeanLineItem=&createQuote%3ApartSearchDial%3AenableAddLine=true&createQuote%3ApartSearchDial%3ApartNumber={PartID}&"
		"createQuote%3ApartSearchDial%3AsearchDlgManufacturerCodeSmart_input=-+Select+One+-&createQuote%3ApartSearchDial%3AsearchDlgCommodityCodeSmart_input=-+Select+One+-&createQuote%3ApartSearchDial%3AselectedPart=&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3ApartNoHidden={PartID}&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3AalternateFl=false&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3AmanufacturerHidden={MFGCD_URL}&"
		"createQuote%3ApartSearchDial%3AsearchPartDataTable_selection=&createQuote%3ApartSearchDial%3ApagePerView=25&createQuote%3AbiSearchDial%3AshipToAccountNo=&createQuote%3AbiSearchDial%3AbillToAccountNo=&createQuote%3AbiSearchDial%3AbiNumber=&createQuote%3AbiSearchDial%3AcustomerTLA=&createQuote%3AbiSearchDial%3Aproject=&createQuote%3AbiSearchDial%3AbiTLAStatusSmart=&createQuote%3AbiSearchDial%3AbiSearchDataTable_selection=&createQuote%3AcreateQuoteErrorMsgs=&createQuote%3AmessagesPanel_collapsed="
		"false&createQuote%3AselectedQuoteType=RFQ&createQuote%3AnationalFlag=false&createQuote%3AinSelInputMethod=Manual&createQuote%3AcustomerFound=false&createQuote%3AidNAcFlag=false&createQuote%3Abilltosmart_input=&createQuote%3AshipToAccount=&createQuote%3AshipToAccountH=&createQuote%3AcontactNameSmart_input=-+Select+One+-&createQuote%3AendCustomerAccount=&createQuote%3AbillToAttention=&createQuote%3AshipToAttention=&createQuote%3AcontactPhone=&createQuote%3AendCustomername=&"
		"createQuote%3AbillToAddress=&createQuote%3AshipToAddress=&createQuote%3AcontactEmail=&createQuote%3AendCustomerCity=&createQuote%3AendCustomerStateProvince=&createQuote%3AendCustomerZip=&createQuote%3AendCustomerCountry=US&createQuote%3AcustomeronDockDate_input={LR_OnDockDate_URL}&createQuote%3AfollowUpDate_input=&createQuote%3AdateDuetoCustomer_input={LR_DueDate_URL}&createQuote%3AdateDuetoSales_input={LR_DueDate_URL}&createQuote%3AprojectBoard=&createQuote%3AcustomerQuote=&"
		"createQuote%3AcustomersHazmatPreference=&createQuote%3AcreditCategory=&createQuote%3AcreditReview=&createQuote%3AresaleCertificate=&createQuote%3AregistrationMatching=Auto+Match&createQuote%3AcreditLimit=&createQuote%3ApaymentTerms=&createQuote%3AstatementofAssurance=&createQuote%3AspecialHandlingCode=&createQuote%3AcreditBalance=&createQuote%3AchannelCode=&createQuote%3AdeniedPartyStatus=&createQuote%3AcreditAvailable=&createQuote%3AtaxIndicator=&createQuote%3AheaderComments=&"
		"createQuote%3AcustomerSearch_collapsed=false&createQuote%3AnewLine=&createQuote%3AlineItems%3A0%3AcustomerPart=&createQuote%3AlineItems%3A0%3ApartNo=&createQuote%3AlineItems%3A0%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A0%3ArequestDescription=&createQuote%3AlineItems%3A0%3Aquantity1=&createQuote%3AlineItems%3A0%3AtargetResale=&createQuote%3AlineItems%3A0%3AquoteResale=&createQuote%3AlineItems%3A0%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A0%3AcustLI=&"
		"createQuote%3AlineItems%3A0%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A0%3AshipToAccount=&createQuote%3AlineItems%3A0%3Acomments=&createQuote%3AlineItems%3A1%3AcustomerPart=&createQuote%3AlineItems%3A1%3ApartNo=&createQuote%3AlineItems%3A1%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A1%3ArequestDescription=&createQuote%3AlineItems%3A1%3Aquantity1=&createQuote%3AlineItems%3A1%3AtargetResale=&createQuote%3AlineItems%3A1%3AquoteResale=&"
		"createQuote%3AlineItems%3A1%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A1%3AcustLI=&createQuote%3AlineItems%3A1%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A1%3AshipToAccount=&createQuote%3AlineItems%3A1%3Acomments=&createQuote%3AlineItems%3A2%3AcustomerPart=&createQuote%3AlineItems%3A2%3ApartNo=&createQuote%3AlineItems%3A2%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A2%3ArequestDescription=&createQuote%3AlineItems%3A2%3Aquantity1=&"
		"createQuote%3AlineItems%3A2%3AtargetResale=&createQuote%3AlineItems%3A2%3AquoteResale=&createQuote%3AlineItems%3A2%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A2%3AcustLI=&createQuote%3AlineItems%3A2%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A2%3AshipToAccount=&createQuote%3AlineItems%3A2%3Acomments=&createQuote%3AlineItems%3A3%3AcustomerPart=&createQuote%3AlineItems%3A3%3ApartNo=&createQuote%3AlineItems%3A3%3AmanufacturerCodeSmart_input=&"
		"createQuote%3AlineItems%3A3%3ArequestDescription=&createQuote%3AlineItems%3A3%3Aquantity1=&createQuote%3AlineItems%3A3%3AtargetResale=&createQuote%3AlineItems%3A3%3AquoteResale=&createQuote%3AlineItems%3A3%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A3%3AcustLI=&createQuote%3AlineItems%3A3%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A3%3AshipToAccount=&createQuote%3AlineItems%3A3%3Acomments=&createQuote%3AlineItems%3A4%3AcustomerPart=&createQuote%3AlineItems%3A4%3ApartNo=&"
		"createQuote%3AlineItems%3A4%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A4%3ArequestDescription=&createQuote%3AlineItems%3A4%3Aquantity1=&createQuote%3AlineItems%3A4%3AtargetResale=&createQuote%3AlineItems%3A4%3AquoteResale=&createQuote%3AlineItems%3A4%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A4%3AcustLI=&createQuote%3AlineItems%3A4%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A4%3AshipToAccount=&createQuote%3AlineItems%3A4%3Acomments=&"
		"createQuote%3AcreateLineItems_collapsed=false&createQuote%3AidHidErrorPresent=false&javax.faces.ViewState={ViewState_URL}", 
		LAST);
	
	lr_end_transaction("BP15_PartSearch_SearchPart", LR_AUTO);

	/*click Close*/

	lr_think_time(9);

	web_add_header("Faces-Request", "partial/ajax");
	web_custom_request("CreateQuote.jsf_4", 
		"URL=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"Resource=0", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t14.inf", 
		"Mode=HTML", 
		"EncType=application/x-www-form-urlencoded; charset=UTF-8", 
		"Body=javax.faces.partial.ajax=true&javax.faces.source=createQuote%3ApartSearchDial%3AremoteCleanPartSearchDataTable&javax.faces.partial.execute=%40all&javax.faces.partial.render=createQuote%3ApartSearchDial%3Aresult&createQuote%3ApartSearchDial%3AremoteCleanPartSearchDataTable=createQuote%3ApartSearchDial%3AremoteCleanPartSearchDataTable&createQuote=createQuote&createQuote%3AcustomDlg%3AcustomerName=&createQuote%3AcustomDlg%3AcustomerAccount_input=&createQuote%3AcustomDlg%3Abranch_input=&"
		"createQuote%3AcustomDlg%3AsearchCustomerDataTable_selection=&createQuote%3AendcustomDlg%3AcustomerName=&createQuote%3AendcustomDlg%3AcustomerAccount_input=&createQuote%3AendcustomDlg%3Abranch_input=&createQuote%3AendcustomDlg%3AsearchCustomerDataTable_selection=&createQuote%3AmisendcustomDlg%3AcustomerName=&createQuote%3AmisendcustomDlg%3AcustomerAccount_input=&createQuote%3AmisendcustomDlg%3Abranch_input=&createQuote%3AmisendcustomDlg%3AsearchCustomerDataTable_selection=&"
		"createQuote%3ApartSearchDial%3AshipToAccountNo=&createQuote%3ApartSearchDial%3AcustomerOnDockDate={LR_OnDockDate_URL}&createQuote%3ApartSearchDial%3AmiscAcctNo=&createQuote%3ApartSearchDial%3AmiscBranch=&createQuote%3ApartSearchDial%3AbeanCustAccountNo=&createQuote%3ApartSearchDial%3AbeanQuantity=&createQuote%3ApartSearchDial%3AbeanCustomerPart=&createQuote%3ApartSearchDial%3AoriginalPartNumber=&createQuote%3ApartSearchDial%3AbeanLineItem=&createQuote%3ApartSearchDial%3AenableAddLine=true&"
		"createQuote%3ApartSearchDial%3ApartNumber=&createQuote%3ApartSearchDial%3AsearchDlgManufacturerCodeSmart_input=-+Select+One+-&createQuote%3ApartSearchDial%3AsearchDlgCommodityCodeSmart_input=-+Select+One+-&createQuote%3ApartSearchDial%3AselectedPart=&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3ApartNoHidden={PartID}&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3AalternateFl=false&createQuote%3ApartSearchDial%3AsearchPartDataTable%3A0%3AmanufacturerHidden={MFGCD_URL}&"
		"createQuote%3ApartSearchDial%3AsearchPartDataTable_selection=&createQuote%3ApartSearchDial%3ApagePerView=25&createQuote%3AbiSearchDial%3AshipToAccountNo=&createQuote%3AbiSearchDial%3AbillToAccountNo=&createQuote%3AbiSearchDial%3AbiNumber=&createQuote%3AbiSearchDial%3AcustomerTLA=&createQuote%3AbiSearchDial%3Aproject=&createQuote%3AbiSearchDial%3AbiTLAStatusSmart=&createQuote%3AbiSearchDial%3AbiSearchDataTable_selection=&createQuote%3AcreateQuoteErrorMsgs=&"
		"createQuote%3AmessagesPanel_collapsed=false&createQuote%3AselectedQuoteType=RFQ&createQuote%3AnationalFlag=false&createQuote%3AinSelInputMethod=Manual&createQuote%3AcustomerFound=false&createQuote%3AidNAcFlag=false&createQuote%3Abilltosmart_input=&createQuote%3AshipToAccount=&createQuote%3AshipToAccountH=&createQuote%3AcontactNameSmart_input=-+Select+One+-&createQuote%3AendCustomerAccount=&createQuote%3AbillToAttention=&createQuote%3AshipToAttention=&createQuote%3AcontactPhone=&"
		"createQuote%3AendCustomername=&createQuote%3AbillToAddress=&createQuote%3AshipToAddress=&createQuote%3AcontactEmail=&createQuote%3AendCustomerCity=&createQuote%3AendCustomerStateProvince=&createQuote%3AendCustomerZip=&createQuote%3AendCustomerCountry=US&createQuote%3AcustomeronDockDate_input={LR_OnDockDate_URL}&createQuote%3AfollowUpDate_input=&createQuote%3AdateDuetoCustomer_input={LR_DueDate_URL}&createQuote%3AdateDuetoSales_input={LR_DueDate_URL}&createQuote%3AprojectBoard=&createQuote%3AcustomerQuote=&"
		"createQuote%3AcustomersHazmatPreference=&createQuote%3AcreditCategory=&createQuote%3AcreditReview=&createQuote%3AresaleCertificate=&createQuote%3AregistrationMatching=Auto+Match&createQuote%3AcreditLimit=&createQuote%3ApaymentTerms=&createQuote%3AstatementofAssurance=&createQuote%3AspecialHandlingCode=&createQuote%3AcreditBalance=&createQuote%3AchannelCode=&createQuote%3AdeniedPartyStatus=&createQuote%3AcreditAvailable=&createQuote%3AtaxIndicator=&createQuote%3AheaderComments=&"
		"createQuote%3AcustomerSearch_collapsed=false&createQuote%3AnewLine=&createQuote%3AlineItems%3A0%3AcustomerPart=&createQuote%3AlineItems%3A0%3ApartNo=&createQuote%3AlineItems%3A0%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A0%3ArequestDescription=&createQuote%3AlineItems%3A0%3Aquantity1=&createQuote%3AlineItems%3A0%3AtargetResale=&createQuote%3AlineItems%3A0%3AquoteResale=&createQuote%3AlineItems%3A0%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A0%3AcustLI=&"
		"createQuote%3AlineItems%3A0%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A0%3AshipToAccount=&createQuote%3AlineItems%3A0%3Acomments=&createQuote%3AlineItems%3A1%3AcustomerPart=&createQuote%3AlineItems%3A1%3ApartNo=&createQuote%3AlineItems%3A1%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A1%3ArequestDescription=&createQuote%3AlineItems%3A1%3Aquantity1=&createQuote%3AlineItems%3A1%3AtargetResale=&createQuote%3AlineItems%3A1%3AquoteResale=&"
		"createQuote%3AlineItems%3A1%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A1%3AcustLI=&createQuote%3AlineItems%3A1%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A1%3AshipToAccount=&createQuote%3AlineItems%3A1%3Acomments=&createQuote%3AlineItems%3A2%3AcustomerPart=&createQuote%3AlineItems%3A2%3ApartNo=&createQuote%3AlineItems%3A2%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A2%3ArequestDescription=&createQuote%3AlineItems%3A2%3Aquantity1=&"
		"createQuote%3AlineItems%3A2%3AtargetResale=&createQuote%3AlineItems%3A2%3AquoteResale=&createQuote%3AlineItems%3A2%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A2%3AcustLI=&createQuote%3AlineItems%3A2%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A2%3AshipToAccount=&createQuote%3AlineItems%3A2%3Acomments=&createQuote%3AlineItems%3A3%3AcustomerPart=&createQuote%3AlineItems%3A3%3ApartNo=&createQuote%3AlineItems%3A3%3AmanufacturerCodeSmart_input=&"
		"createQuote%3AlineItems%3A3%3ArequestDescription=&createQuote%3AlineItems%3A3%3Aquantity1=&createQuote%3AlineItems%3A3%3AtargetResale=&createQuote%3AlineItems%3A3%3AquoteResale=&createQuote%3AlineItems%3A3%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A3%3AcustLI=&createQuote%3AlineItems%3A3%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A3%3AshipToAccount=&createQuote%3AlineItems%3A3%3Acomments=&createQuote%3AlineItems%3A4%3AcustomerPart=&createQuote%3AlineItems%3A4%3ApartNo=&"
		"createQuote%3AlineItems%3A4%3AmanufacturerCodeSmart_input=&createQuote%3AlineItems%3A4%3ArequestDescription=&createQuote%3AlineItems%3A4%3Aquantity1=&createQuote%3AlineItems%3A4%3AtargetResale=&createQuote%3AlineItems%3A4%3AquoteResale=&createQuote%3AlineItems%3A4%3AcustomerOnDockDate_input=&createQuote%3AlineItems%3A4%3AcustLI=&createQuote%3AlineItems%3A4%3ACustomerRef1AFASerialNo=&createQuote%3AlineItems%3A4%3AshipToAccount=&createQuote%3AlineItems%3A4%3Acomments=&"
		"createQuote%3AcreateLineItems_collapsed=false&createQuote%3AidHidErrorPresent=false&javax.faces.ViewState={ViewState_URL}", 
		LAST);

	web_add_header("Faces-Request", "partial/ajax");
	web_submit_data("CreateQuote.jsf_5", 
		"Action=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t15.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=javax.faces.partial.ajax", "Value=true", ENDITEM, 
		"Name=javax.faces.source", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=javax.faces.partial.execute", "Value=createQuote:partSearchDial:dial1", ENDITEM, 
		"Name=javax.faces.behavior.event", "Value=close", ENDITEM, 
		"Name=javax.faces.partial.event", "Value=close", ENDITEM, 
		"Name=createQuote", "Value=createQuote", ENDITEM, 
		"Name=createQuote:customDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:customerOnDockDate", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:partSearchDial:miscAcctNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscBranch", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanQuantity", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustomerPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:originalPartNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanLineItem", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:enableAddLine", "Value=true", ENDITEM, 
		"Name=createQuote:partSearchDial:partNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgManufacturerCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgCommodityCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:selectedPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchPartDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:billToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biNumber", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:customerTLA", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:project", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biTLAStatusSmart", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biSearchDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:createQuoteErrorMsgs", "Value=", ENDITEM, 
		"Name=createQuote:messagesPanel_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:selectedQuoteType", "Value=RFQ", ENDITEM, 
		"Name=createQuote:nationalFlag", "Value=false", ENDITEM, 
		"Name=createQuote:inSelInputMethod", "Value=Manual", ENDITEM, 
		"Name=createQuote:customerFound", "Value=false", ENDITEM, 
		"Name=createQuote:idNAcFlag", "Value=false", ENDITEM, 
		"Name=createQuote:billtosmart_input", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccountH", "Value=", ENDITEM, 
		"Name=createQuote:contactNameSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:endCustomerAccount", "Value=", ENDITEM, 
		"Name=createQuote:billToAttention", "Value=", ENDITEM, 
		"Name=createQuote:shipToAttention", "Value=", ENDITEM, 
		"Name=createQuote:contactPhone", "Value=", ENDITEM, 
		"Name=createQuote:endCustomername", "Value=", ENDITEM, 
		"Name=createQuote:billToAddress", "Value=", ENDITEM, 
		"Name=createQuote:shipToAddress", "Value=", ENDITEM, 
		"Name=createQuote:contactEmail", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCity", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerStateProvince", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerZip", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCountry", "Value=US", ENDITEM, 
		"Name=createQuote:customeronDockDate_input", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:followUpDate_input", "Value=", ENDITEM, 
		"Name=createQuote:dateDuetoCustomer_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:dateDuetoSales_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:projectBoard", "Value=", ENDITEM, 
		"Name=createQuote:customerQuote", "Value=", ENDITEM, 
		"Name=createQuote:customersHazmatPreference", "Value=", ENDITEM, 
		"Name=createQuote:creditCategory", "Value=", ENDITEM, 
		"Name=createQuote:creditReview", "Value=", ENDITEM, 
		"Name=createQuote:resaleCertificate", "Value=", ENDITEM, 
		"Name=createQuote:registrationMatching", "Value=Auto Match", ENDITEM, 
		"Name=createQuote:creditLimit", "Value=", ENDITEM, 
		"Name=createQuote:paymentTerms", "Value=", ENDITEM, 
		"Name=createQuote:statementofAssurance", "Value=", ENDITEM, 
		"Name=createQuote:specialHandlingCode", "Value=", ENDITEM, 
		"Name=createQuote:creditBalance", "Value=", ENDITEM, 
		"Name=createQuote:channelCode", "Value=", ENDITEM, 
		"Name=createQuote:deniedPartyStatus", "Value=", ENDITEM, 
		"Name=createQuote:creditAvailable", "Value=", ENDITEM, 
		"Name=createQuote:taxIndicator", "Value=", ENDITEM, 
		"Name=createQuote:headerComments", "Value=", ENDITEM, 
		"Name=createQuote:customerSearch_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:newLine", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:comments", "Value=", ENDITEM, 
		"Name=createQuote:createLineItems_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:idHidErrorPresent", "Value=false", ENDITEM, 
		"Name=javax.faces.ViewState", "Value={ViewState}", ENDITEM, 
		LAST);

	web_add_header("Faces-Request", "partial/ajax");
	web_submit_data("CreateQuote.jsf_6", 
		"Action=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t16.inf", 
		"Mode=HTML", 
		"EncodeAtSign=YES", 
		ITEMDATA, 
		"Name=javax.faces.partial.ajax", "Value=true", ENDITEM, 
		"Name=javax.faces.source", "Value=createQuote:partSearchDial:closeButton", ENDITEM, 
		"Name=javax.faces.partial.execute", "Value=@all", ENDITEM, 
		"Name=createQuote:partSearchDial:closeButton", "Value=createQuote:partSearchDial:closeButton", ENDITEM, 
		"Name=createQuote", "Value=createQuote", ENDITEM, 
		"Name=createQuote:customDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:customerOnDockDate", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:partSearchDial:miscAcctNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscBranch", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanQuantity", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustomerPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:originalPartNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanLineItem", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:enableAddLine", "Value=true", ENDITEM, 
		"Name=createQuote:partSearchDial:partNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgManufacturerCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgCommodityCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:selectedPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchPartDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:billToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biNumber", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:customerTLA", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:project", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biTLAStatusSmart", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biSearchDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:createQuoteErrorMsgs", "Value=", ENDITEM, 
		"Name=createQuote:messagesPanel_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:selectedQuoteType", "Value=RFQ", ENDITEM, 
		"Name=createQuote:nationalFlag", "Value=false", ENDITEM, 
		"Name=createQuote:inSelInputMethod", "Value=Manual", ENDITEM, 
		"Name=createQuote:customerFound", "Value=false", ENDITEM, 
		"Name=createQuote:idNAcFlag", "Value=false", ENDITEM, 
		"Name=createQuote:billtosmart_input", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccountH", "Value=", ENDITEM, 
		"Name=createQuote:contactNameSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:endCustomerAccount", "Value=", ENDITEM, 
		"Name=createQuote:billToAttention", "Value=", ENDITEM, 
		"Name=createQuote:shipToAttention", "Value=", ENDITEM, 
		"Name=createQuote:contactPhone", "Value=", ENDITEM, 
		"Name=createQuote:endCustomername", "Value=", ENDITEM, 
		"Name=createQuote:billToAddress", "Value=", ENDITEM, 
		"Name=createQuote:shipToAddress", "Value=", ENDITEM, 
		"Name=createQuote:contactEmail", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCity", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerStateProvince", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerZip", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCountry", "Value=US", ENDITEM, 
		"Name=createQuote:customeronDockDate_input", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:followUpDate_input", "Value=", ENDITEM, 
		"Name=createQuote:dateDuetoCustomer_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:dateDuetoSales_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:projectBoard", "Value=", ENDITEM, 
		"Name=createQuote:customerQuote", "Value=", ENDITEM, 
		"Name=createQuote:customersHazmatPreference", "Value=", ENDITEM, 
		"Name=createQuote:creditCategory", "Value=", ENDITEM, 
		"Name=createQuote:creditReview", "Value=", ENDITEM, 
		"Name=createQuote:resaleCertificate", "Value=", ENDITEM, 
		"Name=createQuote:registrationMatching", "Value=Auto Match", ENDITEM, 
		"Name=createQuote:creditLimit", "Value=", ENDITEM, 
		"Name=createQuote:paymentTerms", "Value=", ENDITEM, 
		"Name=createQuote:statementofAssurance", "Value=", ENDITEM, 
		"Name=createQuote:specialHandlingCode", "Value=", ENDITEM, 
		"Name=createQuote:creditBalance", "Value=", ENDITEM, 
		"Name=createQuote:channelCode", "Value=", ENDITEM, 
		"Name=createQuote:deniedPartyStatus", "Value=", ENDITEM, 
		"Name=createQuote:creditAvailable", "Value=", ENDITEM, 
		"Name=createQuote:taxIndicator", "Value=", ENDITEM, 
		"Name=createQuote:headerComments", "Value=", ENDITEM, 
		"Name=createQuote:customerSearch_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:newLine", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:comments", "Value=", ENDITEM, 
		"Name=createQuote:createLineItems_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:idHidErrorPresent", "Value=false", ENDITEM, 
		"Name=javax.faces.ViewState", "Value={ViewState}", ENDITEM, 
		LAST);

	web_add_header("Faces-Request", "partial/ajax");
	web_submit_data("CreateQuote.jsf_7", 
		"Action=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Method=POST", 
		"RecContentType=text/xml", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t17.inf", 
		"Mode=HTML", 
		"EncodeAtSign=YES", 
		ITEMDATA, 
		"Name=javax.faces.partial.ajax", "Value=true", ENDITEM, 
		"Name=javax.faces.source", "Value=createQuote:partSearchDial:remoteCleanPartSearchDataTable", ENDITEM, 
		"Name=javax.faces.partial.execute", "Value=@all", ENDITEM, 
		"Name=javax.faces.partial.render", "Value=createQuote:partSearchDial:result", ENDITEM, 
		"Name=createQuote:partSearchDial:remoteCleanPartSearchDataTable", "Value=createQuote:partSearchDial:remoteCleanPartSearchDataTable", ENDITEM, 
		"Name=createQuote", "Value=createQuote", ENDITEM, 
		"Name=createQuote:customDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:customDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:endcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerName", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:customerAccount_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:branch_input", "Value=", ENDITEM, 
		"Name=createQuote:misendcustomDlg:searchCustomerDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:customerOnDockDate", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:partSearchDial:miscAcctNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:miscBranch", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanQuantity", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanCustomerPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:originalPartNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:beanLineItem", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:enableAddLine", "Value=true", ENDITEM, 
		"Name=createQuote:partSearchDial:partNumber", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgManufacturerCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:searchDlgCommodityCodeSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:partSearchDial:selectedPart", "Value=", ENDITEM, 
		"Name=createQuote:partSearchDial:searchPartDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:shipToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:billToAccountNo", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biNumber", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:customerTLA", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:project", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biTLAStatusSmart", "Value=", ENDITEM, 
		"Name=createQuote:biSearchDial:biSearchDataTable_selection", "Value=", ENDITEM, 
		"Name=createQuote:createQuoteErrorMsgs", "Value=", ENDITEM, 
		"Name=createQuote:messagesPanel_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:selectedQuoteType", "Value=RFQ", ENDITEM, 
		"Name=createQuote:nationalFlag", "Value=false", ENDITEM, 
		"Name=createQuote:inSelInputMethod", "Value=Manual", ENDITEM, 
		"Name=createQuote:customerFound", "Value=false", ENDITEM, 
		"Name=createQuote:idNAcFlag", "Value=false", ENDITEM, 
		"Name=createQuote:billtosmart_input", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:shipToAccountH", "Value=", ENDITEM, 
		"Name=createQuote:contactNameSmart_input", "Value=- Select One -", ENDITEM, 
		"Name=createQuote:endCustomerAccount", "Value=", ENDITEM, 
		"Name=createQuote:billToAttention", "Value=", ENDITEM, 
		"Name=createQuote:shipToAttention", "Value=", ENDITEM, 
		"Name=createQuote:contactPhone", "Value=", ENDITEM, 
		"Name=createQuote:endCustomername", "Value=", ENDITEM, 
		"Name=createQuote:billToAddress", "Value=", ENDITEM, 
		"Name=createQuote:shipToAddress", "Value=", ENDITEM, 
		"Name=createQuote:contactEmail", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCity", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerStateProvince", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerZip", "Value=", ENDITEM, 
		"Name=createQuote:endCustomerCountry", "Value=US", ENDITEM, 
		"Name=createQuote:customeronDockDate_input", "Value={LR_OnDockDate}", ENDITEM, 
		"Name=createQuote:followUpDate_input", "Value=", ENDITEM, 
		"Name=createQuote:dateDuetoCustomer_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:dateDuetoSales_input", "Value={LR_DueDate}", ENDITEM, 
		"Name=createQuote:projectBoard", "Value=", ENDITEM, 
		"Name=createQuote:customerQuote", "Value=", ENDITEM, 
		"Name=createQuote:customersHazmatPreference", "Value=", ENDITEM, 
		"Name=createQuote:creditCategory", "Value=", ENDITEM, 
		"Name=createQuote:creditReview", "Value=", ENDITEM, 
		"Name=createQuote:resaleCertificate", "Value=", ENDITEM, 
		"Name=createQuote:registrationMatching", "Value=Auto Match", ENDITEM, 
		"Name=createQuote:creditLimit", "Value=", ENDITEM, 
		"Name=createQuote:paymentTerms", "Value=", ENDITEM, 
		"Name=createQuote:statementofAssurance", "Value=", ENDITEM, 
		"Name=createQuote:specialHandlingCode", "Value=", ENDITEM, 
		"Name=createQuote:creditBalance", "Value=", ENDITEM, 
		"Name=createQuote:channelCode", "Value=", ENDITEM, 
		"Name=createQuote:deniedPartyStatus", "Value=", ENDITEM, 
		"Name=createQuote:creditAvailable", "Value=", ENDITEM, 
		"Name=createQuote:taxIndicator", "Value=", ENDITEM, 
		"Name=createQuote:headerComments", "Value=", ENDITEM, 
		"Name=createQuote:customerSearch_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:newLine", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:0:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:1:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:2:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:3:comments", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerPart", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:partNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:manufacturerCodeSmart_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:requestDescription", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quantity1", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:targetResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:quoteResale", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:customerOnDockDate_input", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:custLI", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:CustomerRef1AFASerialNo", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:shipToAccount", "Value=", ENDITEM, 
		"Name=createQuote:lineItems:4:comments", "Value=", ENDITEM, 
		"Name=createQuote:createLineItems_collapsed", "Value=false", ENDITEM, 
		"Name=createQuote:idHidErrorPresent", "Value=false", ENDITEM, 
		"Name=javax.faces.ViewState", "Value={ViewState}", ENDITEM, 
		LAST);

	/*logout*/
	
	lr_start_transaction("SMR_Logout");

	web_url("j_spring_security_logout", 
		"URL=http://qrt-staging.avnet.com/qrtapp/j_spring_security_logout", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://qrt-staging.avnet.com/qrtapp/pages/smx/CreateQuote.jsf?conversationContext=1", 
		"Snapshot=t18.inf", 
		"Mode=HTML", 
		LAST);


	web_url("pkmslogout", 
		"URL=https://edge-test.avnet.com/pkmslogout", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://edge-test.avnet.com/pkmslogout?filename=qrt-stage-logout.htm", 
		"Snapshot=t20.inf", 
		"Mode=HTML", 
		LAST);

	web_add_cookie("PD-H-SESSION-ID=; DOMAIN=edge-test.avnet.com");

	web_add_cookie("JSESSIONID=; DOMAIN=edge-test.avnet.com");

	web_add_cookie("PD-ECC=; DOMAIN=edge-test.avnet.com");

	web_add_cookie("ONTCred=; DOMAIN=edge-test.avnet.com");

	web_url("qrtapp_2", 
		"URL=http://qrt-staging.avnet.com/qrtapp", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://edge-test.avnet.com/pkmslogout?filename=qrt-stage-logout.htm", 
		"Snapshot=t21.inf", 
		"Mode=HTML", 
		LAST);


	web_url("eaidologin_3", 
		"URL=https://edge-test.avnet.com/eai/EAIavnet/eaidologin", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://edge-test.avnet.com/vouchfor?avnet&http://qrt-staging.avnet.com/qrtapp", 
		"Snapshot=t22.inf", 
		"Mode=HTML", 
		LAST);
	
	lr_end_transaction("SMR_Logout", LR_AUTO);

	return 0;
}
